version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=local
      - PORT=5000
    volumes:
      - /app/node_modules
      - ./backend:/app

  mongo:
    image: mongo
    ports:
      - 27017:27017

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING="true"
    volumes:
      - /app/node_modules
      - ./frontend:/app

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
